from tkinter import *
from tkinter import messagebox
import os
import math
window=Tk()
window.geometry("460x600")
window.title("Calculator")
window.iconbitmap(r'C:\Users\DIVVELA VISHNU\Downloads\calculator icon1.ico')
label=Label(window,text="CALCULATOR",bg="yellow",font=("Times",30,"bold"),fg="red")
label.pack(side=TOP)
window.config(background="yellow")
textin=StringVar()
operator=""

def clickbut(number):
    global operator
    operator = operator + str(number)
    textentry.insert(len(textentry.get()),str(number))
def history1():
    global operator
    his=textentry.get()
    sol1=str(eval(textentry.get()))
    all_history=os.listdir()
    new_file=open("History","a")
    new_file.write(his+ '=')
    new_file.write(sol1+'\n')
    new_file.close()
def history2():
    file1=open("History","r")
    file1_data=file1.read()
    history_details=file1_data.split("\n")
    messagebox.showinfo("History","{}\n".format(history_details[::-1]))

def equalbut(*args):
    try:
        global operator
        history1()
        sol=str(eval(textentry.get()))
        textin.set(sol)
        operator=sol
    except:
        messagebox.showinfo("Calculator","User given Entry is Wrong Syntax, Please Enter correct syntax If you dont know then just press on options and press on about")
def clrbut(*args):
    global operator
    textentry.delete(0,END)
    operator=''
def backspace():
    global operator
    back=textentry.get()
    length=len(back)
    back=back[0:length-1]
    textentry.delete(0,END)
    textentry.insert(0,back)
    operator=back
def Exit1():
    Exit1=messagebox.askyesno("Calculator","confirm if you want to exit")
    if Exit1 > 0:
        window.destroy()
        exit()
def abt():
    messagebox.showinfo("Calculator","This is a project for a Simple Calculator you can use all options related to an simple calculator \n*In Log function to find value(x) with respect to base(y) then the function is log(x,y) \n*For Sin,cos,tan functions after giving value please press '))' Button also\n*In any Funtion if any bracket is opened like '(' then balance every open bracket that with ')' ")
def clear_history():
    file2=open("History","w")
    file2.close()
def key_event(*args):
    v=textentry.get()
    v=str(v)
    #textentry.insert(len(textentry.get()),v[-1])
       
textentry=Entry(window,font=("Courier New",12,"bold"),textvar=textin,width=42,insertwidth=3,bd=10,bg="Powder blue")
textentry.bind("<Return>",equalbut)
textentry.bind("<Key-1>",key_event)
textentry.bind("<Key-2>",key_event)
textentry.bind("<Key-3>",key_event)
textentry.bind("<Key-4>",key_event)
textentry.bind("<Key-5>",key_event)
textentry.bind("<Key-6>",key_event)
textentry.bind("<Key-7>",key_event)
textentry.bind("<Key-8>",key_event)
textentry.bind("<Key-9>",key_event)
textentry.bind("<Key-0>",key_event)
textentry.bind("<Key-.>",key_event)
textentry.focus_set()
textentry.pack()

but1=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut(1),text="1",font=("Courier New",16,"bold"))
but1.place(x=10,y=100)
but2=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut(2),text="2",font=("Courier New",16,"bold"))
but2.place(x=10,y=170)
but3=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut(3),text="3",font=("Courier New",16,"bold"))
but3.place(x=10,y=240)
but4=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut(4),text="4",font=("Courier New",16,"bold"))
but4.place(x=75,y=100)
but5=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut(5),text="5",font=("Courier New",16,"bold"))
but5.place(x=75,y=170)
but6=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut(6),text="6",font=("Courier New",16,"bold"))
but6.place(x=75,y=240)
but7=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut(7),text="7",font=("Courier New",16,"bold"))
but7.place(x=140,y=100)
but8=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut(8),text="8",font=("Courier New",16,"bold"))
but8.place(x=140,y=170)
but9=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut(9),text="9",font=("Courier New",16,"bold"))
but9.place(x=140,y=240)
but0=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut(0),text="0",font=("Courier New",16,"bold"))
but0.place(x=10,y=310)
butdot=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut("."),text=".",font=("Courier New",16,"bold"))
butdot.place(x=75,y=310)
butplus=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut("+"),text="+",font=("Courier New",16,"bold"))
butplus.place(x=205,y=100)
butsub=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut("-"),text="-",font=("Courier New",16,"bold"))
butsub.place(x=205,y=170)
butmul=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut("*"),text="*",font=("Courier New",16,"bold"))
butmul.place(x=205,y=240)
butdiv=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut("/"),text="/",font=("Courier New",16,"bold"))
butdiv.place(x=205,y=310)
butclear=Button(window,padx=14,pady=119,bd=4,bg="white",command=clrbut,text="CE",font=("Courier New",16,"bold"))
butclear.place(x=270,y=100)
buteql=Button(window,padx=14,pady=14,bd=4,bg="white",command=equalbut,text="=",font=("Courier New",16,"bold"))
buteql.place(x=140,y=310)
butsin=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut("math.sin("),text="sin(",font=("Arial",12,"bold"))
butsin.place(x=10,y=380)
butradians=Button(window,padx=14,pady=16,bd=4,bg="white",command=lambda:clickbut("math.radians("),text="radians",font=("Arial",12,"bold"))
butradians.place(x=347,y=100)
butcos=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut("math.cos("),text="cos(",font=("Arial",12,"bold"))
butcos.place(x=85,y=380)
buttan=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut("math.tan("),text="tan(",font=("Arial",12,"bold"))
buttan.place(x=165,y=380)
butlog=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut("math.log("),text="log(",font=("Arial",12,"bold"))
butlog.place(x=240,y=380)
bute=Button(window,padx=20,pady=14,bd=4,bg="white",command=lambda:clickbut("math.e"),text="e",font=("Arial",12,"bold"))
bute.place(x=315,y=380)
butpi=Button(window,padx=17,pady=14,bd=4,bg="white",command=lambda:clickbut("math.pi"),text="π",font=("Arial",12,"bold"))
butpi.place(x=382,y=380)
butinsin=Button(window,padx=15,pady=17,bd=4,bg="white",command=lambda:clickbut("math.asin("),text="  sin-1  ",font=("Arial",12,"bold"))
butinsin.place(x=347,y=168)
butincos=Button(window,padx=14,pady=17,bd=4,bg="white",command=lambda:clickbut("math.acos("),text="  cos-1  ",font=("Arial",12,"bold"))
butincos.place(x=347,y=239)
butintan=Button(window,padx=15,pady=17,bd=4,bg="white",command=lambda:clickbut("math.atan("),text="  tan-1  ",font=("Arial",12,"bold"))
butintan.place(x=347,y=310)
butpow=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut("**"),text="pow",font=("Arial",12,"bold"))
butpow.place(x=10,y=445)
butparansis=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut("))"),text="))",font=("Arial",12,"bold")).place(x=90,y=445)
butparansis1=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut("("),text="(",font=("Arial",12,"bold")).place(x=147,y=445)
butparansis2=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut(")"),text=")",font=("Arial",12,"bold")).place(x=200,y=445)
butfact=Button(window,padx=14,pady=14,bd=4,bg="white",command=lambda:clickbut("math.factorial("),text="fact",font=("Arial",12,"bold")).place(x=253,y=445)
butroot=Button(window,padx=12,pady=14,bd=4,bg="white",command=lambda:clickbut("math.sqrt("),text="√x",font=("Arial",12,"bold")).place(x=327,y=445)
butroot=Button(window,padx=12,pady=14,bd=4,bg="white",command=lambda:clickbut("%"),text="%",font=("Arial",12,"bold")).place(x=388,y=445)
butbackspace=Button(window,padx=12,pady=14,bd=4,bg="white",command=backspace,text="<-Back",font=("Arial",12,"bold"))
butbackspace.place(x=10,y=510)
butcomma=Button(window,padx=12,pady=14,bd=4,bg="white",command=lambda:clickbut(","),text="comma",font=("Arial",12,"bold"))
butcomma.place(x=104,y=510)
buthistory=Button(window,padx=12,pady=14,bd=4,bg="white",command=history2,text="history",font=("Arial",12,"bold"))
buthistory.place(x=203,y=510)
butinvx=Button(window,padx=12,pady=14,bd=4,bg="white",command=lambda:clickbut("1/"),text="1/x",font=("Arial",12,"bold"))
butinvx.place(x=297,y=510)
butdegrees=Button(window,padx=19,pady=14,bd=4,bg="white",command=lambda:clickbut("math.degrees("),text="Deg",font=("Arial",12,"bold"))
butdegrees.place(x=360,y=510)
menu=Menu(window)
window.config(menu=menu)
submenu1=Menu(window)
menu.add_cascade(label="File",menu=submenu1)
submenu1.add_command(label="Clear History",command=clear_history)
submenu1.add_separator()
submenu1.add_command(label="Exit",command=Exit1)
submenu2=Menu(window)
menu.add_cascade(label="Options",menu=submenu2)
submenu2.add_command(label="About",command=abt)
window.mainloop()
